### ISSUE TITLE
Criar módulo que aplique a barra e rodapé oficial do governo federal

### ISSUE THREAD

**Issue by nitaibezerra** [redelivre/wp-divi#1]
Disponibilizar módulo que aplique automaticamente a barra oficial e o rodapé aos sites do governo federal. A utilização é obrigatória e normatizada pela SECOM.

A barra tem o carregamento dinâmico garantindo sempre a utilização da versão mais atual. A utilização da barra desta forma facilita a aderência às normas. Por exemplo, em época de eleição todos os sites devem remover a marca de governo de seus sites correndo o risco de serem penalizados. A marca de governo acompanha o rodapé e é modificada de maneira centralizada.

Mais infos de como aplicar http://barra.brasil.gov.br/

**Comment by jpmehl** [comment]
Acredito que isto pode ser resolvido com as próprias soluções do DIVI,
basta configurar o cabeçalho é rodapé e transforma-los em "global"
Em 13 de jun de 2016 8:51 PM, "Nitai Bezerra da Silva" <
notifications@github.com> escreveu:

**Comment by nitaibezerra** [comment]
Iríamos seguir essa estratégia, João Paulo. Porém o Jacson foi mais rápido e criou um plugin do WP independente do DIVI pra aplicar a barra brasil. Aqui https://github.com/redelivre/wp-barra-brasil
